version: 0.0
os: linux

files:
  - source: / # 전체 파일을 의미
    destination: /home/ubuntu/wonnapark
    overwrite: yes
permissions:
  - object: /home/ubuntu/wonnapark
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu